# Site settings
title: Deadlock
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Deadlock explores technical ideas, tools and curiosities. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://deadlock.icu" # the base hostname & protocol for your site
twitter_username: losneanu
github_username:  mercer

# Build settings
markdown: kramdown
